---
apiVersion: v1
kind: Secret
metadata:
  name: psdi-glorius-plot-sa-secret
  annotations:
    kubernetes.io/service-account.name: psdi-glorius-plot-admin-sa
type: kubernetes.io/service-account-token
