apiVersion: apps/v1
kind: Deployment
metadata:
  name: psdi-reaction-radar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psdi-reaction-radar
  template:
    metadata:
      labels:
        app: psdi-reaction-radar
      annotations:
        elastic.co/dataset: kubernetes.container_logs.psdi_reaction_radar
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - psdi-reaction-radar
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: psdi-reaction-radar
          image: psdi-reaction-radar
          volumeMounts:
            - mountPath: /tmp
              name: uploads
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi" # this value may need to increase if application stability declines
              cpu: "1000m"
      imagePullSecrets:
        - name: github-psdi-registry-credentials
      volumes:
        - name: uploads
          emptyDir:
            sizeLimit: 1Gi
