---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psdi-glorius-plot-admin-role-binding
subjects:
  - kind: ServiceAccount
    name: psdi-glorius-plot-admin-sa
roleRef:
  kind: Role
  name: psdi-glorius-plot-admin-role
  apiGroup: rbac.authorization.k8s.io
