---
apiVersion: v1
kind: Secret
metadata:
  name: psdi-reaction-radar-sa-secret
  annotations:
    kubernetes.io/service-account.name: psdi-reaction-radar-admin-sa
type: kubernetes.io/service-account-token
