# Workflow for continuous integration tasks triggered on pushes to main

name: CI - Main
run-name: CI - Main
on:
  workflow_dispatch:
    inputs:
      skip-tests:
        description: "Don't run tests before deploying"
        required: false
        default: false
        type: boolean
  push:
    branches: ["main"]
    paths:
      - "**/ci-main.yml"
      - "psdi_glorius_plot/**"
      - "tests/**"
      - "Dockerfile"
      - "pyproject.toml"

jobs:
  test-all:
    if: ${{ github.event_name == 'push' || ! github.event.inputs.skip-tests }}
    uses: PSDI-UK/psdi-github-workflows-public/.github/workflows/test-all.yml@13d6eb8fb4d93382eb1743ed51baf939f160c474
    with:
      source_dir: psdi_glorius_plot
      make_coverage_badge: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  container-push:
    uses: PSDI-UK/psdi-github-workflows-public/.github/workflows/container-push.yml@13d6eb8fb4d93382eb1743ed51baf939f160c474
    needs: [test-all]
    # Proceed if test-all was successful or skipped
    if: always() &&  (needs.test-all.result == 'skipped' || needs.test-all.result == 'success')
    with:
      container_tag: ${{ github.sha }}
      service_name: psdi_glorius_plot
      rel_url_path: /glorius-plot
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  # Deploy to Kubernetes Job
  # Requires an environment, which must reflect the target environment as defined in the
  # GitHub repository: https://github.com/PSDI-UK/psdi-glorius-plot/settings/environments
  # The downstream deploy job leverages on Environment specific secrets, which also must be defined
  # For the tag, we need something unique for each push, so we use the SHA of the latest commit
  deploy-stfc-dev-k8s:
    needs: [container-push]
    # Proceed if test-all was successful or skipped
    if: always() && (needs.container-push.result == 'success')
    uses: PSDI-UK/psdi-github-workflows-public/.github/workflows/deploy.yml@13d6eb8fb4d93382eb1743ed51baf939f160c474
    with:
      container_tag: ${{ github.sha }}
      deployment_repo: DEPLOYMENT_REPO_NAME
      deployment_ref: DEPLOYMENT_REPO_REF
      environment: development
      prod: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      deployment_app_id: ${{ secrets.DEPLOYMENT_APP_ID }}
      deployment_app_private_key: ${{ secrets.DEPLOYMENT_APP_PRIVATE_KEY }}
