# WARNING: Renaming this file will cause the deployment to PyPI and TestPyPI to fail until the new name is added to both
# in their Trusted Publisher Management (available in the in the Publishing section of the project management page)
#
# Workflow for continuous integration tasks triggered on push to release

name: CI - Release
run-name: CI - Release
on:
  workflow_dispatch:
  push:
    branches: ["release"]

jobs:
  test-python:
    uses: PSDI-UK/psdi-github-workflows-public/.github/workflows/test-python.yml@bf05a4bd1ea45d81bae78abe18a9a32ea87eee24
    with:
      source_dir: psdi_glorius_plot
  test-gui:
    name: Run full tests of the gui locally
    uses: PSDI-UK/psdi-github-workflows-public/.github/workflows/test-gui.yml@bf05a4bd1ea45d81bae78abe18a9a32ea87eee24
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  # The commented out code below runs a code vulnerability scan on the
  # containerised app. This will not work on the free GitHub plan, since
  # for that plan code scanning is not supported for private repos - and
  # this is a private repo. There may be a work-around.
  #
  # NOTE: If you uncomment this job to use it you may wish to change the
  # 'needs' in the below 'tag-container-push' job from 'test-package'
  # to 'anchore-scan' if you want to make a release dependent on a successful
  # scan.
  #
  #anchore-scan:
  #  uses: PSDI-UK/psdi-glorius-plot-deployment/.github/workflows/anchore-scan.yml@bf05a4bd1ea45d81bae78abe18a9a32ea87eee24
  #  needs: [test-package, test-gui]

  tag:
    uses: PSDI-UK/psdi-github-workflows-public/.github/workflows/tag.yml@bf05a4bd1ea45d81bae78abe18a9a32ea87eee24
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  container-push:
    uses: PSDI-UK/psdi-github-workflows-public/.github/workflows/container-push.yml@bf05a4bd1ea45d81bae78abe18a9a32ea87eee24
    needs: [tag]
    with:
      container_tag: ${{ needs.tag.outputs.container_tag }}
      service_name: psdi_glorius_plot
      rel_url_path: /glorius-plot
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  # Deploy to Kubernetes Job
  # Requires an environment, which must reflect the target environment as defined in the
  # GitHub repository: https://github.com/PSDI-UK/psdi_glorius_plot/settings/environments
  # The downstream deploy job leverages on Environment specific secrets, which also must be defined
  deploy-stfc-staging-k8s:
    needs: [tag, container-push]
    uses: PSDI-UK/psdi-glorius-plot-deployment/.github/workflows/job-external-deployment.yaml@bf95f7bc0840247a40dbd8aef2aaa7ee2baad1fe
    with:
      container_tag: ${{ needs.tag.outputs.container_tag }}
      environment: staging
    secrets:
      deployment_app_id: ${{ secrets.DEPLOYMENT_APP_ID }}
      deployment_app_private_key: ${{ secrets.DEPLOYMENT_APP_PRIVATE_KEY }}
